---
ID: "15284c6b-6497-49d3-889c-1271300569ee"
Parent: "493c34ed-611a-4280-a8dd-b3d33c71745f"
Template: "f036b5e0-37fb-4537-9d36-ef84e5bd41b7"
Path: /sitecore/system/Settings/Foundation/Training/Training Headless Site Collection Setup
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20240814T082615Z
    - ID: "52807595-0f8f-4b20-8d2a-cb71d28c6103"
      Hint: __Owner
      Value: |
        sitecore\dnanavati@horizontal.com
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\dnanavati@horizontal.com
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "85893311-e21a-43d8-8ddc-10a85e13c14f"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\dnanavati@horizontal.com
    - ID: "c202067e-7fab-4606-afb4-e76df2185ddc"
      Hint: Name
      Value: Training
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20240814T082615Z
